const items = [
  { icon: '◉', title: 'Proactive blocklist tracking', text: 'Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.' },
  { icon: '▱', title: 'Faster time to inbox', text: 'Send emails from the region closest to your users. Reduce delivery latency with North American, South American, European, and Asian regions.' },
  { icon: '♧', title: 'Build confidence with BIMI', text: 'Showcase your logo and company branding with BIMI. Receive guidance to obtain a VMC, the email equivalent of a checkmark on social media.' },
  { icon: '◎', title: 'Managed dedicated IPs', text: 'Get a fully managed dedicated IP that automatically warms up and autoscales based on your sending volume, no waiting period.' },
  { icon: '♨', title: 'Dynamic suppression list', text: 'Prevent repeated sending to recipients who no longer want your email and comply with standards like the CAN-SPAM Act and others.' },
  { icon: '⚙', title: 'IP and domain monitoring', text: 'Monitor your DNS configuration for any errors or regressions. Be notified of any changes that could hinder your deliverability.' },
  { icon: '▤', title: 'Verify DNS records', text: 'Protect your reputation by verifying your identity as a legitimate sender. Secure your email communication using DKIM and SPF.' },
  { icon: '♢', title: 'Battle-tested infrastructure', text: "Rely on a platform of reputable IPs used by trustworthy senders with distributed workloads across different IP pools." },
  { icon: '🛡', title: 'Prevent spoofing with DMARC', text: 'Avoid impersonation by creating DMARC policies and instructing inbox providers on how to treat unauthenticated email.' },
]

export function Deliverability() {
  return (
    <section className="deliverability-section" id="deliverability">
      <h2>
        Reach humans, not<br />
        <em>spam folders</em>
      </h2>
      <div className="deliverability-grid">
        {items.map((item) => (
          <article className="deliverability-item" key={item.title}>
            <span className="deliverability-icon">{item.icon}</span>
            <h3>{item.title}</h3>
            <p>{item.text}</p>
          </article>
        ))}
      </div>
    </section>
  )
}
