import {
  Ban,
  Inbox,
  Award,
  Earth,
  Hand,
  Globe,
  Server,
  Shield,
  HatGlasses,
} from 'lucide-react'

const items = [
  { icon: Ban, title: 'Proactive blocklist tracking', text: 'Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.' },
  { icon: Inbox, title: 'Faster time to inbox', text: 'Send emails from the region closest to your users. Reduce delivery latency with North American, South American, European, and Asian regions.' },
  { icon: Award, title: 'Build confidence with BIMI', text: 'Showcase your logo and company branding with BIMI. Receive guidance to obtain a VMC, the email equivalent of a checkmark on social media.' },
  { icon: Earth, title: 'Managed dedicated IPs', text: 'Get a fully managed dedicated IP that automatically warms up and autoscales based on your sending volume, no waiting period.' },
  { icon: Hand, title: 'Dynamic suppression list', text: 'Prevent repeated sending to recipients who no longer want your email and comply with standards like the CAN-SPAM Act and others.' },
  { icon: Globe, title: 'IP and domain monitoring', text: 'Monitor your DNS configuration for any errors or regressions. Be notified of any changes that could hinder your deliverability.' },
  { icon: Server, title: 'Verify DNS records', text: 'Protect your reputation by verifying your identity as a legitimate sender. Secure your email communication using DKIM and SPF.' },
  { icon: Shield, title: 'Battle-tested infrastructure', text: "Rely on a platform of reputable IPs used by trustworthy senders with distributed workloads across different IP pools." },
  { icon: HatGlasses, title: 'Prevent spoofing with DMARC', text: 'Avoid impersonation by creating DMARC policies and instructing inbox providers on how to treat unauthenticated email.' },
]

export function Deliverability() {
  return (
    <section className="deliverability-section" id="deliverability">
      <h2>
        Reach humans, not<br />
        <em>spam folders</em>
      </h2>
      <div className="deliverability-grid">
        {items.map(({ icon: Icon, title, text }) => (
          <article className="deliverability-item" key={title}>
            <span className="deliverability-icon">
              <Icon size={22} strokeWidth={1.5} />
            </span>
            <h3>{title}</h3>
            <p>{text}</p>
          </article>
        ))}
      </div>
    </section>
  )
}